[[headers]]
  for = "/*" # you can configure the correct paths here
  [headers.values]
    Cache-Control = "no-cache"
    access-control-allow-origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
