[[headers]]
  for = "https://julioparra-cv.netlify.app/cv-minimalist/_astro/hoisted.BOqlnksF.js" # you can configure the correct paths here
  [headers.values]
    Cache-Control = "no-cache"
    access-control-allow-origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
